# Generated by Django 4.1.1 on 2022-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='data_files_folder')),
            ],
            options={
                'verbose_name': 'Файл выгрузки',
                'verbose_name_plural': 'Файлы выгрузки',
            },
        ),
    ]
