# Generated by Django 4.1.1 on 2022-11-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_file',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='data_file',
            name='data',
            field=models.FileField(upload_to='main_part/data_files_folder/'),
        ),
    ]
