# Generated by Django 4.1.1 on 2022-11-16 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_part', '0002_data_file_comment_alter_data_file_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rjaka', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь приложения',
                'verbose_name_plural': 'Пользователи приложения',
            },
        ),
    ]
