# Generated by Django 4.1.1 on 2022-11-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0005_data_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_file',
            name='is_public',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
