# Generated by Django 4.1.1 on 2022-11-17 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0006_data_file_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_file',
            name='file_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_file',
            name='file_name',
            field=models.CharField(default='Filename', max_length=100),
            preserve_default=False,
        ),
    ]
