# Generated by Django 4.1.3 on 2022-11-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0007_data_file_file_created_at_data_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_file',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
