# Generated by Django 4.1.2 on 2022-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0008_alter_data_file_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app_user',
            old_name='rjaka',
            new_name='token',
        ),
        migrations.AddField(
            model_name='app_user',
            name='token_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
