# Generated by Django 4.1.2 on 2023-01-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_part', '0009_rename_rjaka_app_user_token_app_user_token_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_intersection_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.FileField(upload_to='main_part/data_files_folder/temporary_user_intersection_files/')),
            ],
        ),
        migrations.AlterField(
            model_name='app_user',
            name='token',
            field=models.CharField(blank=True, default='abscence of token', max_length=300),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='token_date',
            field=models.DateTimeField(blank=True, default='1970-01-01 04:00:02', null=True),
        ),
    ]
